#PROJECT 8 - Rock paper scissors program

def rps():

    print ("Welcome to my rock paper scissors game!")
    username1 = input ("Player 1 name: ")
    username2 = input ("Player 2 name: ")  
   
    userchoice1 = input ("{}, make your choice: rock,paper or scissors ".format(username1))
    userchoice2 = input ("{}, make your choice: rock,paper or scissors ".format(username2))

    if userchoice1 == "rock" and userchoice2 == "paper":
        print("{} wins!".format(username2))
    elif userchoice1 == "rock" and userchoice2 == "scissors":
        print("{} wins!".format(username1))
    elif userchoice1 == "paper" and userchoice2 == "scissors":
        print("{} wins!".format(username2))
    elif userchoice1 == "paper" and userchoice2 == "rock":
        print("{} wins!".format(username1))
    elif userchoice1 == "scissors" and userchoice2 == "rock":
        print("{} wins!".format(username2))
    elif userchoice1 == "scissors" and userchoice2 == "paper":
        print("{} wins!".format(username1))

    gamelist = ["rock","paper","scissors"]
    if userchoice1 not in gamelist:
        print("{}, choose one of the following options (rock,paper,scissors) ".format(username1))
        rps()
    if userchoice2 not in gamelist:
        print("{}, choose one of the following options (rock,paper,scissors) ".format(username2))
        rps()

    if userchoice1 == userchoice2:
        print("its a tie! Nobody wins this time")
        rps()


    while True:
        answer = input ("Do you want to play again? yes/no \n")
        if answer == "yes":
            rps()
        elif answer == "no":
            print("Thanks for trying me out!")
            menu()
        else:
            print("Please answer by yes or no")
            rps()
   

#PROJECT 7 - Random word out of a word list
def generator():
    import random
    print("Welcome to my random word generator!")
    username = input ("What's your name?")
    print("Hi {}!Your randomly generated word is : ".format(username))

    print(random.choice(open("wordlist.txt").read().split()))

    while True:
        answer = input ("Do you want to generate another word? yes/no \n")
        if answer == "yes":
            generator()
        elif answer == "no":
            print("Thanks for trying me out!")
            menu()
        else:
            print("Please answer by yes or no")
            generator()


#PROJECT 6 - Dice rolling game
def dicerolling():
    import random
    print("Welcome to my rolling dice game!")
    username = input ("What's your name? ")
    dice1 = random.randint(1,6)
    dice2 = random.randint(1,6)
    print("{}, dices has been thrown! The numbers are : ".format(username), dice1, "and ", dice2)

    while True:
        answer = input ("Do you want to roll dices again? yes/no \n")
        if answer == "yes":
            dicerolling()
        elif answer == "no":
            print("Thanks for trying me out!")
            menu()
        else:
            print("Please answer by yes or no")
            dicerolling()
     

#PROJECT 5 - List generated by player sorted in alphabetically order

def listsort():
    print("Welcome to list sortation!")
    username = input ("What's your name?")
    print("Hi {}!".format(username))
    useranswer = input ("{} please, give me your random list of words and I am gonna sort it out for you in alphabetical order!".format(username))
    useranswer = useranswer.split()
    useranswer.sort()
    for x in useranswer:
        print(x)
   
    while True:
        answer = input ("Do you want to create another list? yes/no \n")
        if answer == "yes":
           listsort()
        elif answer == "no":
            print("Thanks for trying me out!")
            menu()
        else:
            print("Please answer by yes or no")
            listsort()
    
    
#PROJECT 4 - Finding the largest number from the giben
def max():
    print("Welcome to max number finder!")
    username = input ("What's your name?")
    print("Hi {}!".format(username))
    print ("{} please, give me your random numbers and im gonna find the biggest one!".format(username))
    num1 = int(input("Give me your first number: "))
    num2 = int(input("Give me your second number: "))
    num3 = int(input("Give me your third number: "))
    if num1 > num2 and num1 > num3:
        largest = num1
    elif num2 > num1 and num2 > num3:
        largest = num2
    else:
        largest = num3

    print("The biggest number is :" , largest)

    while True:
        answer = input ("Do you want to find another number? yes/no \n")
        if answer == "yes":
           max()
        elif answer == "no":
            print("Thanks for trying me out!")
            menu()
        else:
            print("Please answer by yes or no")
            max()
    



#PROJECT 3 - Multiplication table 
def table():
    print("Welcome to multiplication table!")
    username = input ("What's your name?")
    print("Hi {}!".format(username))
    print ("{} please, give me your number and im gonna make a multiplication table for it !".format(username))
    userchoice = float(input("What's the number you want to multiplicate? "))
    i = 1
    while i <= 12:
        print(i * userchoice)
        i+=1
    print("{}, your multiplication of  ".format(username), userchoice , " can be found above ")


    while True:
        answer = input ("Do you want to multiply another number? yes/no \n")
        if answer == "yes":
           table()
        elif answer == "no":
            print("Thanks for trying me out!")
            menu()
        else:
            print("Please answer by yes or no")
            table()

#PROJECT 2 - Area of a triangle

def trianglearea():
    print("Welcome to calculating area of triangle program!")
    username = input ("What's your name?")
    print("Hi {}!".format(username))
    print ("{} please, give me height and base of a triangle, and I'm gonna calculate area of it!".format(username))
    triangle_height = float(input("What's the height of the triangle? "))
    triangle_base = float(input("What's the base of the triangle? "))
    print("{}, your area of triangle equals to : " .format(username), 1/2 * triangle_height * triangle_base )

    while True:
        answer = input ("Do you want to calculate another area of a triangle? yes/no \n")
        if answer == "yes":
           trianglearea()
        elif answer == "no":
            print("Thanks for trying me out!")
            menu()
        else:
            print("Please answer by yes or no")
            trianglearea()





#PROJECT 1 - Simple calculator 

def Add(x,y):
    return x + y
def Sub(x,y):
    return x - y 
def Multi(x,y):
    return x * y
def Div(x,y):
    return x / y


def calculator():
    print("Welcome to simple my simple calculator!")
    username = input ("What's your name?")
    print("Hi {}!".format(username))
    print ("Tell me, what do you want to do ?")
    choice = input ("""
                1.Addition
                2.Substraction
                3.Multiplication
                4.Division
                """)
    if choice == "1":
        x = float(input ("give me first number "))
        y = float(input ("give me second number "))
        print ("Your result equals to : ", Add(x,y))
    elif choice == "2":
        x = float(input ("give me first number "))
        y = float(input ("give me second number" ))
        print ("Your result equals to : ", Sub(x,y))
    elif choice == "3":
        x = float(input ("give me first number "))
        y = float(input ("give me second number "))
        print ("Your result equals to : ", Multi(x,y))
    elif choice == "4":
        x = float(input ("give me first number "))
        y = float(input ("give me second number "))
        print ("Your result equals to : ", Div(x,y))
    else:
        input("Please choose one of the following options: number 1 - 4")
        calculator()

    while True:
        answer = input ("Do you want to use calculator again? yes/no \n")
        if answer == "yes":
           calculator()
        elif answer == "no":
            print("Thanks for trying me out!")
            menu()
        else:
            print("Please answer by yes or no")
            calculator()
    

def menu():
    print("\nWelcome to my first python project!\n")
    username = input ("What's your name?\n")
    print("This is menu of 8 different games you can choose from\n")
    print("Hi {}!, what do you want to do?".format(username))
    userchoice = input (""" 
                        1.Rock,Paper,Scissors game
                        2.Generate random word from a list
                        3.Dice Rolling Game! :D
                        4.Alphabetical list sortation
                        5.Finding the highest number
                        6.Multiplication table
                        7.Calculating area of a triangle
                        8.Simple Calculator
                        Anything else will close the porogram
                        """)
    while True:
        if userchoice == "1":
            rps()
        elif userchoice == "2":
            generator()
        elif userchoice == "3":
            dicerolling()
        elif userchoice == "4":
            listsort()
        elif userchoice == "5":
            max()
        elif userchoice == "6":
            table()
        elif userchoice == "7":
            trianglearea()
        elif userchoice == "8":
            calculator()
        else:
            break
       
menu()

         


     


